#!/bin/bash

ST=$(dropbox-cli status)
RN=$(dropbox-cli running)

ARR=()
ARR+=("Status: $ST")
ARR+=("	Start")
ARR+=("	Stop")
ARR+=("Proxy:")
ARR+=("	None")
ARR+=("	Auto")
ARR+=("	Proxy")

CHOICE=$(printf '%s\n' "${ARR[@]}" | rofi -dmenu -config /home/chew/.config/i3/rofi/dropbox -p "Dropbox Menu")

if [ "$CHOICE" = "	Start" ]; then
	dropbox-cli start
	exit 0
fi

if [ "$CHOICE" = "	Stop" ]; then
	dropbox-cli stop
	exit 0
fi

if [ "$CHOICE" = "	None" ]; then
	dropbox-cli proxy none
	exit 0
fi

if [ "$CHOICE" = "	Auto" ]; then
	dropbox-cli proxy auto
	exit 0
fi

if [ "$CHOICE" = "	Proxy" ]; then
	dropbox-cli proxy manual http 192.168.31.19 8080 1201371 8245
	exit 0
fi
